<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateQuoteRequestsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('quote_requests', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->text('name')->nullable();
            $table->text('phone_number')->nullable();
            $table->text('email_address')->nullable();
            $table->text('property_type')->nullable();
            $table->text('moving_from')->nullable();
            $table->text('post_code_from')->nullable();
            $table->text('moving_to')->nullable();
            $table->text('post_code_to')->nullable();
            $table->text('parking_dist')->nullable();
            $table->text('lounge_sofa')->nullable();
            $table->text('lounge_armchair')->nullable();
            $table->text('lounge_bookcase')->nullable();
            $table->text('lounge_coffee_table')->nullable();
            $table->text('lounge_nest_of_tables')->nullable();
            $table->text('lounge_lamp')->nullable();
            $table->text('lounge_cabinet')->nullable();
            $table->text('lounge_music_system')->nullable();
            $table->text('lounge_television')->nullable();
            $table->text('lounge_rugs')->nullable();
            $table->text('lounge_pictures')->nullable();
            $table->text('lounge_boxes_packed')->nullable();
            $table->text('lounge_boxes')->nullable();
            $table->text('dining_cabinet')->nullable();
            $table->text('dining_dresser')->nullable();
            $table->text('dining_desk')->nullable();
            $table->text('dining_bureau')->nullable();
            $table->text('dining_table')->nullable();
            $table->text('dining_chairs')->nullable();
            $table->text('dining_sideboard')->nullable();
            $table->text('dining_piano')->nullable();
            $table->text('dining_cabinet_corner')->nullable();
            $table->text('dining_bookcase')->nullable();
            $table->text('dining_chairs_easy')->nullable();
            $table->text('dining_pictures')->nullable();
            $table->text('dining_boxes_packed')->nullable();
            $table->text('dining_boxes')->nullable();
            $table->text('kitchen_microwave')->nullable();
            $table->text('kitchen_fridge_freezer')->nullable();
            $table->text('kitchen_washing_machine')->nullable();
            $table->text('kitchen_dryer')->nullable();
            $table->text('kitchen_dishwasher')->nullable();
            $table->text('kitchen_fridge')->nullable();
            $table->text('kitchen_freezer')->nullable();
            $table->text('kitchen_chest_freezer')->nullable();
            $table->text('kitchen_table')->nullable();
            $table->text('kitchen_chairs')->nullable();
            $table->text('kitchen_dresser')->nullable();
            $table->text('kitchen_boxes_packed')->nullable();
            $table->text('kitchen_boxes')->nullable();
            $table->text('cons_sofa')->nullable();
            $table->text('cons_armchairs')->nullable();
            $table->text('cons_bookcase')->nullable();
            $table->text('cons_coffee_table')->nullable();
            $table->text('cons_television')->nullable();
            $table->text('cons_boxes_packed')->nullable();
            $table->text('cons_boxes')->nullable();
            $table->text('hall_table')->nullable();
            $table->text('hall_bookcase')->nullable();
            $table->text('hall_trunk')->nullable();
            $table->text('hall_rugs')->nullable();
            $table->text('hall_pictures')->nullable();
            $table->text('hall_boxes_packed')->nullable();
            $table->text('hall_boxes')->nullable();
            $table->text('bed1_wardrobe_single')->nullable();
            $table->text('bed1_wardrobe_double')->nullable();
            $table->text('bed1_bed_double')->nullable();
            $table->text('bed1_bed_single')->nullable();
            $table->text('bed1_chest')->nullable();
            $table->text('bed1_dressing')->nullable();
            $table->text('bed1_ottoman')->nullable();
            $table->text('bed1_tallboy')->nullable();
            $table->text('bed1_computer_desk')->nullable();
            $table->text('bed1_television')->nullable();
            $table->text('bed1_bookcase')->nullable();
            $table->text('bed1_boxes')->nullable();
            $table->text('bed1_wardrobe_cartons')->nullable();
            $table->text('bed2_wardrobe_single')->nullable();
            $table->text('bed2_wardrobe_double')->nullable();
            $table->text('bed2_bed_double')->nullable();
            $table->text('bed2_bed_single')->nullable();
            $table->text('bed2_chest')->nullable();
            $table->text('bed2_dressing')->nullable();
            $table->text('bed2_ottoman')->nullable();
            $table->text('bed2_tallboy')->nullable();
            $table->text('bed2_computer_desk')->nullable();
            $table->text('bed2_television')->nullable();
            $table->text('bed2_bookcase')->nullable();
            $table->text('bed2_boxes')->nullable();
            $table->text('bed2_wardrobe_cartons')->nullable();
            $table->text('bed3_wardrobe_single')->nullable();
            $table->text('bed3_wardrobe_double')->nullable();
            $table->text('bed3_bed_double')->nullable();
            $table->text('bed3_bed_single')->nullable();
            $table->text('bed3_chest')->nullable();
            $table->text('bed3_dressing')->nullable();
            $table->text('bed3_ottoman')->nullable();
            $table->text('bed3_tallboy')->nullable();
            $table->text('bed3_computer_desk')->nullable();
            $table->text('bed3_television')->nullable();
            $table->text('bed3_bookcase')->nullable();
            $table->text('bed3_boxes')->nullable();
            $table->text('bed3_wardrobe_cartons')->nullable();
            $table->text('bed4_wardrobe_single')->nullable();
            $table->text('bed4_wardrobe_double')->nullable();
            $table->text('bed4_bed_double')->nullable();
            $table->text('bed4_bed_single')->nullable();
            $table->text('bed4_chest')->nullable();
            $table->text('bed4_dressing')->nullable();
            $table->text('bed4_ottoman')->nullable();
            $table->text('bed4_tallboy')->nullable();
            $table->text('bed4_computer_desk')->nullable();
            $table->text('bed4_television')->nullable();
            $table->text('bed4_bookcase')->nullable();
            $table->text('bed4_boxes')->nullable();
            $table->text('bed4_wardrobe_cartons')->nullable();
            $table->text('garage_tool_boxes')->nullable();
            $table->text('garage_workbench')->nullable();
            $table->text('garage_racking')->nullable();
            $table->text('garage_timber')->nullable();
            $table->text('garage_cabinets')->nullable();
            $table->text('garage_bicycles')->nullable();
            $table->text('garage_ladders')->nullable();
            $table->text('garage_step_ladders')->nullable();
            $table->text('garden_mower')->nullable();
            $table->text('garden_strimmer')->nullable();
            $table->text('garden_roller')->nullable();
            $table->text('garden_wheel_barrow')->nullable();
            $table->text('garden_dustbins')->nullable();
            $table->text('garden_tools')->nullable();
            $table->text('garden_bench')->nullable();
            $table->text('garden_bbq')->nullable();
            $table->text('garden_tables')->nullable();
            $table->text('garden_chairs')->nullable();
            $table->text('garden_loungers')->nullable();
            $table->text('garden_swing')->nullable();
            $table->text('garden_pots_large')->nullable();
            $table->text('garden_pots_small')->nullable();
            $table->text('garden_ornaments')->nullable();
            $table->text('garden_other')->nullable();
            $table->text('loft_contents')->nullable();
            $table->text('cupboard_contents')->nullable();
            $table->text('auth_code')->nullable();
            $table->integer('seen', 0);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('quote_requests');
    }
}
